services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    networks:
      - spring-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:80
      - 1025:25

networks:
  spring-network:
    driver: bridge

volumes:
    postgres:
        driver: local